name: Rebase Knative Operator

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  nightly-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Knative Operator Project
        uses: actions/checkout@v4
        with: 
          path: operator
          repository: patrickleet/knative-operator

      # Add your custom steps here
      - name: Rebase from upstream
        run: |
          cd operator
          git remote add upstream git@github.com:knative/operator.git
          git fetch --all --tags
          git rebase upstream/main --autostash
          git push origin main --force
