name: Rebase Knative Operator

on:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  rebase-knative-operator:
    runs-on: ubuntu-latest

    steps:
      - name: Rebase from upstream
        run: |
          git clone https://github.com/patrickleet/knative-operator.git
          cd knative-operator
          git remote add upstream https://github.com/knative/operator.git
          git fetch --all --tags
          git rebase upstream/main --autostash
          git push origin main --force
